import fs from 'fs';
import path from 'path';

export function generateMarkdown(targetDir: string, mermaidGraph: string, title: string = 'Codebase Architecture'): void {
  const docsDir = path.join(targetDir, 'docs');
  
  if (!fs.existsSync(docsDir)) {
    fs.mkdirSync(docsDir, { recursive: true });
  }

  const content = `# ${title}

This document outlines the architecture and dependency graph of the codebase, automatically generated by CodeAtlas.

## Dependency Graph

\`\`\`mermaid
${mermaidGraph}
\`\`\`

## Notes
- 📄 **Internal Modules**: Files within the project.
- 📦 **External Dependencies**: NPM packages or external modules.
`;

  const outputPath = path.join(docsDir, 'architecture.md');
  fs.writeFileSync(outputPath, content, 'utf8');
}
