import fs from 'fs';
import path from 'path';

export function generateMarkdown(targetDir: string, mermaidGraph: string, lang: 'en' | 'zh' = 'en'): void {
  const docsDir = path.join(targetDir, 'docs');
  
  if (!fs.existsSync(docsDir)) {
    fs.mkdirSync(docsDir, { recursive: true });
  }

  const isZh = lang === 'zh';
  const title = isZh ? '代码库架构图' : 'Codebase Architecture';
  const desc = isZh 
    ? '本文档展示了当前代码库的架构和依赖关系图，由 CodeAtlas 自动生成。'
    : 'This document outlines the architecture and dependency graph of the codebase, automatically generated by CodeAtlas.';
  const depTitle = isZh ? '依赖关系图' : 'Dependency Graph';
  const notesTitle = isZh ? '图例说明' : 'Notes';
  const noteInternal = isZh ? '📄 **内部模块**: 项目内部的代码文件。' : '📄 **Internal Modules**: Files within the project.';
  const noteExternal = isZh ? '📦 **外部依赖**: NPM 依赖包或其他外部模块。' : '📦 **External Dependencies**: NPM packages or external modules.';

  const content = `# ${title}

${desc}

## ${depTitle}

\`\`\`mermaid
${mermaidGraph}
\`\`\`

## ${notesTitle}
- ${noteInternal}
- ${noteExternal}
`;

  const outputPath = path.join(docsDir, 'architecture.md');
  fs.writeFileSync(outputPath, content, 'utf8');
}
